# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20161009_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('href', models.CharField(max_length=320)),
            ],
            options={
                'db_table': 'navigation',
            },
        ),
    ]
